### PR TITLE
Adding data demo

### PR DESCRIPTION
**Pull request by diazrenata**
Here's a second draft of the adding/updating data demo!

A couple things -
Making a Zenodo release seems like a separate step from adding/updating data. I've never interacted with Zenodo, but happy to figure out how to make a release and add that step if that seems like the way to go.
Links/screenshots only seem to work if I put /static/ at the beginning of the path, even though I don't see that in the ones Ethan put in?

### CODE REVIEW

**Review by gmyenni — COMMENTED** [review]
Awesome!!! Thanks for this!

The /static/ links don't work in the preview, but maybe that's just a preview thing? 

Was there something remaining with releases on Zenodo that we should make an issue for?

**Comment by ethanwhite** [comment]
> The /static/ links don't work in the preview, but maybe that's just a preview thing?

The preview is rendered just like the real site, so this is something that needs to be fixed.

**Comment by gmyenni** [comment]
Also, @diazrenata , there are two step 6's. Can you update the numbering? Thanks!

**Comment by gmyenni** [comment]
Great, thanks!!

**Pull request merged**
